# LIB88 Makefile
#

#INCLUDES=-I/usr/include -I/usr/include/c86
#DEFINES=
#CPPFLAGS=-0 $(INCLUDES) $(DEFINES)
#CPP=$(BIN)cpp

##### Standardized section of Makefile #####

CC=$(BIN)c88
C2=$(BIN)gen88
AS=$(BIN)asm88
AR=$(BIN)lib88
LD=$(BIN)link88

# Automated rules for C88 toolchain
.c.o:
	#$(CPP) $(CPPFLAGS) $*.c -o $*.i
	$(CC) $*.c PW
	$(C2) $* Z
	#$(AS) $*.as L

.s.o:
	$(AS) $*.s L

##### End of standardized section #####

PROG=lib88
OBJS=       \
    LIB88.o \

all: $(OBJS) $(PROG)

$(PROG): $(OBJS)
	$(LD) $^ -Olib88 -Plib88.lst -_ -HFFFF
	cp lib88 $(DSROOT)/bin2

clean:
	rm -f *.i *.as *.o *.a *.lst $(PROG)
