# ASM88 Makefile
#

BIN=/root/
#INCLUDES=-I/usr/include -I/usr/include/c86
#DEFINES=
#CPPFLAGS=-0 $(INCLUDES) $(DEFINES)
#CPP=$(BIN)cpp

##### Standardized section of Makefile #####

CC=$(BIN)c88
C2=$(BIN)gen88
AS=$(BIN)asm88
AR=$(BIN)lib88
LD=$(BIN)link88

# Automated rules for C88 toolchain
.c.o:
	#$(CPP) $(CPPFLAGS) $*.c -o $*.i
	$(CC) $*.c PW
	$(C2) $* Z
	#$(AS) $*.as L

.s.o:
	$(AS) $*.s L

##### End of standardized section #####

PROG=asm88.bin
OBJS=       \
    ASM88.o \
    ASM2.o  \
    ASM3.o  \
    ASM4.o  \
    ASM5.o  \

all: $(OBJS) $(PROG)

$(PROG): $(OBJS)
	$(LD) $^ -Oasm88 -Pasm88.lst -_ -S7FFE
	cp asm88.bin /root/dasm88

clean:
	rm -f *.i *.as *.o *.a *.lst $(PROG)
