;
; ELKS system call numbers
; Must be kept synchronized with elks/arch/i86/kernel/syscall.dat
;

SYS_exit           equ    1
SYS_fork           equ    2
SYS_read           equ    3
SYS_write          equ    4
SYS_open           equ    5
SYS_close          equ    6
SYS_wait4          equ    7
;;SYS_creat        equ    8
SYS_link           equ    9
SYS_unlink         equ   10
SYS_execve         equ   11
SYS_chdir          equ   12
;;SYS_time         equ   13
SYS_mknod          equ   14
SYS_chmod          equ   15
SYS_chown          equ   16
SYS_brk            equ   17
SYS_stat           equ   18
SYS_lseek          equ   19
SYS_getpid         equ   20
SYS_mount          equ   21
SYS_umount         equ   22
SYS_setuid         equ   23
SYS_getuid         equ   24
;;SYS_stime        equ   25
;;SYS_ptrace       equ   26
SYS_alarm          equ   27
SYS_fstat          equ   28
;;SYS_pause        equ   29
SYS_utime          equ   30
SYS_chroot         equ   31
SYS_vfork          equ   32
SYS_access         equ   33
;;SYS_nice         equ   34
;;SYS_sleep        equ   35
SYS_sync           equ   36
SYS_kill           equ   37
SYS_rename         equ   38
SYS_mkdir          equ   39
SYS_rmdir          equ   40
SYS_dup            equ   41
SYS_pipe           equ   42
;;SYS_times        equ   43
;;SYS_prof         equ   44
SYS_dup2           equ   45
SYS_setgid         equ   46
SYS_getgid         equ   47
SYS_signal         equ   48
;;SYS_getinfo      equ   49
SYS_fcntl          equ   50
;;SYS_acct         equ   51
;;SYS_phys         equ   52
;;SYS_lock         equ   53
SYS_ioctl          equ   54
SYS_reboot         equ   55
;;SYS_mpx          equ   56
SYS_lstat          equ   57
SYS_symlink        equ   58
SYS_readlink       equ   59
SYS_umask          equ   60
SYS_settimeofday   equ   61
SYS_gettimeofday   equ   62
SYS_select         equ   63
SYS_readdir        equ   64
;;SYS_insmod       equ   65
SYS_fchown         equ   66
;;SYS_dllload      equ   67
SYS_setsid         equ   68
SYS_sbrk           equ   69
SYS_ustatfs        equ   70
SYS_setitimer      equ   71
SYS_sysctl         equ   72
;;
SYS_uname          equ   74
SYS_socket         equ   75
SYS_bind           equ   76
SYS_listen         equ   77
SYS_accept         equ   78
SYS_connect        equ   79
SYS_setsockopt     equ   80
SYS_getsocknam     equ   81
SYS_fmemalloc      equ   82
SYS_fmemfree       equ   83
