# 'make' Makefile
#

#INCLUDES=-I/usr/include -I/usr/include/c86
#DEFINES=
#CPPFLAGS=-0 $(INCLUDES) $(DEFINES)
#CPP=$(BIN)cpp

##### Standardized section of Makefile #####

CC=$(BIN)c88
C2=$(BIN)gen88
AS=$(BIN)asm88
AR=$(BIN)lib88
LD=$(BIN)link88

CFLAGS = $(CLBASE) $(WARNINGS) $(LOCALFLAGS)

# Automated rules for C88 toolchain
.c.o:
	#$(CPP) $(CPPFLAGS) $*.c -o $*.i
	$(CC) $*.c PW $(CFLAGS)
	$(C2) $* Z
	#$(AS) $*.as L

.s.o:
	$(AS) $*.s L

##### End of standardized section #####

PROG=make
LOCALFLAGS = -Dunix
xLIBC = ../libc/stdio/fgetc.o ../libc/stdio/__fopen.o ../libc/misc/memcpy.o ../libc/builtin/cmp4.o ../libc/builtin/switch.o ../libc/builtin/muldiv.o
OBJS = check.o input.o macro.o main.o make.o reader.o rules.o

xLIBC = ../libc/*/*.a
LIBC = ../libc/cstdio.a

all: $(OBJS) $(PROG)

$(PROG): $(OBJS)
	$(LD) $^ $(LIBC) -O$(PROG) -P$(PROG).lst -_ -H4000
	cp $(PROG) $(DSROOT)/bin2

clean:
	rm -f *.i *.as *.o *.a *.lst $(PROG)
