#
# DCC Makefile on ELKS
#

DIRS = libc C GEN ASM NBIND LIB88 OTHER

all:
	for DIR in $(DIRS); do cd $$DIR; $(MAKE) all || exit 1; cd ..; done
	sync

clean:
	for DIR in $(DIRS); do cd $$DIR; $(MAKE) clean || exit 1; cd ..; done

